apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base

replicas:
  - name: vote
    count: 4

images:
  - name: schoolofdevops/vote
    newTag: v4

namespace: instavote

commonLabels:
  project: instavote
  env: staging

commonAnnotations:
  supported-by: "seth"

patches:
  - target:
      kind: Service
      name: vote
    path: service.yaml