apiVersion: v1
kind: Service
metadata:
  labels:
    app: vote
  name: vote
spec:
  ports:
  - name: "http"
    nodePort: 30000
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: vote
  type: NodePort
status:
  loadBalancer: {}
