apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base

replicas:
  - name: vote
    count: 1

images:
  - name: schoolofdevops/vote
    newTag: v5

namespace: instavote

commonLabels:
  project: instavote
  env: dev

commonAnnotations:
  supported-by: "seth"

# configMapGenerator:
#   - 